"""
References:
    - https://en.wikipedia.org/wiki/Subdivisions_of_Sierra_Leone
    - https://en.wikipedia.org/wiki/Districts_of_Sierra_Leone
    - https://en.wikipedia.org/wiki/Chiefdoms_of_Sierra_Leone
    - https://reliefweb.int/updates?source=1503&format=12.12570&advanced-search=(PC211)#content

Notes:
    - Two new districts, Falaba and Karene, were introduced in 2017.
        - https://en.wikipedia.org/wiki/Falaba_District
        - https://en.wikipedia.org/wiki/Karene_District
        - The number of Chiefdoms also increased from 149 to 190.
        - We are concerned with the structure from 2014.

Issues:
    - How to handle Bo Town. It's not really a Chiefdom, but seems to be a separate entity?
        - Seems to be split into 3 Wards, each with several sections.
    - Do the Western Urban and Western Rural districts have Chiefdoms?
"""

#
# Forward mappings (larger -> smaller)
#
province2districts = {
    'Eastern': ['Kailahun', 'Kenema', 'Kono'],
    'North West': ['Kambia', 'Karene', 'Port Loko'],
    'Northern': ['Bombali', 'Falaba', 'Koinadugu', 'Tonkolili'],
    'Southern': ['Bo', 'Bonthe', 'Moyamba', 'Pujehun'],
    'Western': ['Western Rural', 'Western Urban'],
}

district2chiefdoms = {
    'Bo': [
        'Badjia',
        'Bagbo',
        'Bagbwe',
        'Baoma',
        'Bumpe Ngao',
        'Gbo',
        'Jaiama Bongor',
        'Kakua',
        'Komboya',
        'Lugbu',
        'Niawa Lenga',
        'Selenga',
        'Tikonko',
        'Valunia',
        'Wonde',
    ],
    'Bombali': [
        'Biriwa',
        'Bombali Shebora',
        'Gbanti Kamaranka',
        'Gbendembu Ngowahun',
        'Libeisaygahun',
        'Magbaiamba Ndowahun',
        'Makari Gbanti',
        'Paki Massabong',
        'Safroko Limba',
        'Sanda Loko',
        'Sanda Tenraren',
        'Sella Limba',
        'Tambakha',
    ],
    'Bonthe': [
        'Bendu',
        'Bum',
        'Dema',
        'Imperri',
        'Jong',
        'Kongoba Bullom',
        'Kpanda',
        'Kwamebai Krim',
        'Sittia',
        'Songbini',
        'Yawbeko',
    ],
    'Kailahun': [
        'Dea',
        'Jaluahun',
        'Jawei',
        'Kissi Kama',
        'Kissi Teng',
        'Kissi Tongi',
        'Luawa',
        'Malema',
        'Mandu',
        'Peje Bongre',
        'Peje West',
        'Penguia',
        'Upper Bambara',
        'Yawei',
    ],
    'Kambia': [
        'Brimaia',
        'Gbinle Dixing',
        'Magbema',
        'Mambolo',
        'Masungbala',
        'Samu',
        'Tonko Limba',
    ],
    'Kenema': [
        'Dama',
        'Dodo',
        'Gaura',
        'Gorama Mende',
        'Kandu Leppiam',
        'Koya',
        'Langurama Ya',
        'Lower Bambara',
        'Malegohun',
        'Niawa',
        'Nomo',
        'Nongowa',
        'Simbaru',
        'Small Bo',
        'Tunkia',
        'Wando',
    ],
    'Koinadugu': [
        'Dembelia Sikunia',
        'Diang',
        'Folasaba',
        'Kasunko',
        'Mongo',
        'Neya',
        'Nieni',
        'Sengbe',
        'Sulima',
        'Wara-Wara Bafodea',
        'Wara-Wara Yagala',
    ],
    'Kono': [
        'Fiama',
        'Gbane Kandor',
        'Gbane',
        'Gbense',
        'Gorama Kono',
        'Kamara',
        'Lei',
        'Mafindor',
        'Nimikoro',
        'Nimiyama',
        'Sandor',
        'Soa',
        'Tankoro',
        'Toli',
    ],
    'Moyamba': [
        'Bagruwa',
        'Banta',
        'Bumpe',
        'Dasse',
        'Fakunya',
        'Kagboro',
        'Kaiyamba',
        'Kamajei',
        'Kongbora',
        'Kori',
        'Kowa',
        'Ribbi',
        'Timdale',
        'Upper Banta',
    ],
    'Port Loko': [
        'Bureh Kasseh',
        'Buya Romende',
        'Debia',
        'Kaffu Bullom',
        'Koya',
        'Loko Masama',
        'Maforki',
        'Marampa'
        'Masimera',
        'Sanda Magbolontor',
        'T.M. Safroko',
    ],
    'Pujehun': [
        'Barri',
        'Gallines Perri',
        'Kpaka',
        'Kpanga Kabonde',
        'Kpanga Krim',
        'Makpele',
        'Malen',
        'Mano Sa Krim',
        'Peje',
        'Soro Gbema',
        'Sowa',
        'Yakemo Kpukumu Krim',
    ],
    'Tonkolili': [
        'Gbonkolenken',
        'Kafe Simiria',
        'Kalansongoia',
        'Kholifa Mabang',
        'Kholifa Rowalla',
        'Kunike Barina',
        'Kunike',
        'Malal Mara',
        'Sambaia',
        'Tane',
        'Yoni',
    ],
    'Western Rural': [
        'Koya Rural',
        'Mountain Rural',
        'Waterloo Rural',
        'York Rural',
    ],
    'Western Urban': [
        'Central 1',
        'Central 2',
        'East 1',
        'East 2',
        'East 3',
        'West 1',
        'West 2',
        'West 3',
    ],
}

chiefdom2sections = {
    'Badjia': [
        # Possibly one more section, missing name on map
        'Damal',
        'Kpallay',
        'Njargbahun',
        'Sei',
    ],
    'Bagbo': [
        'Bum',
        'Gorapon',
        'Jimmi',
        'Kpangballa',
        'Mano',
        'Niagorehun',
        'Tissana',
    ],
    'Bagbwe': [
        # Possibly one more section, missing name on map
        'Jongo',
        'Niawa',
        'Nyallay',
        'Samawa',
    ],
    'Baoma': [
        'Bambawo',
        'Fallay',
        'Kimaya',
        'Lower Pataloo',
        'Mawojeh',
        'Njeima',
        'Sonnah',
        'Upper Pataloo',
    ],
    'Bapewa': [],
    'Barri': [],
    'Bendu-cha': [
        'Gba-cha',
        'Sokenteh',
        'Tissagbe',
        'Yallan-gbokie',
    ],
    'Biriwa': [
        'Balandugu',
        'Bumban',
        'Bumbandain',
        'Kabakeh',
        'Kagbankuna',
        'Kamabai',
        'Karassa',
        'Karina',
        'Kayonkoro',
    ],
    'Bombali Shebora': [
        'Kafala',
        'Kagbaran Dokom',
        'Konta',
        'Matotoka',
    ],
    'Bonthe Municipal': [],
    'Bramaia': [
        'Banguraia',
        'Bassia',
        'Bugami',
        'Duramania',
        'Filligungee',
        'Fortumboyie',
        'Gberekhuray',
        'Gbolon',
        'Kabaya',
        'Kanku Bramaia',
        'Konta',
        'Kua Bramaia',
        'Kufuru',
        'Kukuna',
        'Laminaia',
        'Sansangie',
        'Seduya',
        'Shekaia',
        'Sulaimania',
        'Teneba Bramaia',
        'Turaya',
    ],
    'Bum': [
        'Fikie',
        'Gbengain',
        'Gbondubum',
        'Koimato',
        'Lanje',
        'Tamba',
        'Torma',
        'Yargbe',
        'Yawma',
    ],
    'Bumpe': [],
    'Bumpe Ngao': [
        'Bongo',
        'Bumpe',
        'Foya',
        'Kpetema',
        'Sahn',
        'Serabu',
        'Sewama',
        'Taninahun',
        'Walihun',
        'Yengema',
    ],
    'Buya Romende': [],
    'Chepo': [],
    'Dasse': [],
    'Dea': [
        'Baiwalla',
        'Dodo',
        'Sakiema',
        'Sienga',
    ],
    'Debia': [],
    'Dama': [
        'Dakowa',
        'Danyadejo',
        'Dassama',
        'Fowai',
        'Fowai',
        'Klajie',
        'Lower Dabor',
        'Upper Dabor',
    ],
    'Dema': [
        'Chepo',
        'Dema',
        'Turtle Islands',
        'Yoh',
    ],
    'Dembelia Sinkunia': [
        'Kunbulun 1',
        'Kunbulun 2',
        'Manan',
        'Mawundea',
        'Numula 1',
        'Numula 2',
        'Numula 3',
        'Numula 4',
        'Numula 5',
        'Sinkunia',
    ],
    'Diang': [
        'Darakuru',
        'Gbenekoro',
        'Kania',
        'Kondembaia',
        'Lengekoro',
        'Sokurala',
    ],
    'Dodo': [
        # Possibly two additional sections, missing names on map
        'Bambara',
        'Gorama',
        'Karteh',
        'Korgay',
        'Seiwor',
    ],
    'Fakunya': [],
    'Fiama': [],
    'Folosaba Dembelia': [
        'Balandugu',
        'Dogoloya',
        'Fissaya 1',
        'Fissaya 2',
        'Gbentu 3',
        'Herekor',
        'Kalia',
        'Kamba',
        'Lagor',
        'Musaia',
        'Sankan 1',
        'Sankan 2',
    ],
    'Gallines Perri': [],
    'Gaura': [
        'Geibu',
        'Joru',
        'Kokoru',
        'Mendekelema',
        'Sandaru',
        'Sembehun',
    ],
    'Gbakahun': [],
    'Gbane': [],
    'Gbane Kandor': [],
    'Gbanti Kamarank': [
        'Gbenkfay',
        'Gbonkobana',
        'Kambia',
        'Kayourgbor',
        'Makulon',
        'Makumray A',
        'Makumray B',
        'Royeama A',
        'Royeama B',
        'Sakuma A',
        'Sakuma B',
        'Sendugu A',
        'Sendugu B',
    ],
    'Gbap': [],
    'Gbayafe': [],
    'Gbendembu Ngowahun': [
        'Garanganwa',
        'Gbendembu',
        'Kalangba',
        'Kania',
        'Lobanga',
        'Lohindie',
        'Loko-Madina',
        'Makai',
        'Makarihiteh',
        'Makeregbohun',
        'Makump',
        'Mamaka',
        'Mamukay',
        'Masongbo',
        'Matehun',
        'Mayorthan',
        'Sahun',
        'Tambiama',
        'Tanyehun',
    ],
    'Gbense': [],
    'Gbinleh Dixing': [
        'Gbinle',
        'Kalangba',
        'Katalan',
        'Mafaray',
        'Maton',
        'Rogberay',
        'Sanda',
        'Tawuya',
    ],
    'Gbo': [
        'Gbo',
        'Maryu',
        'Nyawa',
    ],
    'Gbomoti': [],
    'Gbonkolenken': [],
    'Gorama Kono': [],
    'Gorama Mende': [
        'Biatong',
        'Famanjo',
        'Kaklawa',
        'Kualley',
    ],
    'Imperri': [
        'Babum',
        'Bapus',
        'Bigo',
        'Kahekay',
        'Moimaligie',
        'Sokrapan',
    ],
    'Jaiama Bongor': [
        'Lower Baimba',
        'Lower Kama',
        'Lower Niawa',
        'Nekpondo',
        'Tongowa',
        'Upper Baimba',
        'Upper Kama',
        'Upper Niawa',
    ],
    'Jassande Keifema': [],
    'Jawei': [
        'Sowa',
        'Kaio',
        'Mano',
        'Bobor',
        'Upper Luyengeh',
        'Lower Luyengeh',
        'Upper Geibu',
        'Lower Geibu',
    ],
    'Jong': [
        'Basiaka',
        'Bayengbe',
        'Beyinga',
        'Falewuja',
        'Kumabeh-Kwe',
        'Landi-Ngere',
        'Sopan-Cleveland',
        'Tucker-Nyambe',
    ],
    'Kafe Simiria': [],
    'Kaffu-Bullom': [],
    'Kaiyamba': [],
    'Kaiyamba Fakunya': [],
    'Kakua': [
        # Possibly two more sections, missing names on map
        'Korjeh',
        'Kpandobu',
        'Nguabu',
        'Samamie',
        'Sewa',
        'Sindeh',
    ],
    'Kalansogoia': [],
    'Kandu Leppiama': [
        'Borley',
        'Gboro-Lokoma',
        'Karga',
        'Sonnie',
    ],
    'Kamara': [],
    'Kasunko': [
        'Gbonkobor',
        'Kakallain',
        'Kasunko',
        'Kayaka',
        'Tamiso 1',
        'Tamiso 2',
    ],
    'Kemoh': [],
    'Kholifa Mabang': [],
    'Kholifa Rowalla': [],
    'Kissi Kama': [
        'Dakaleley',
        'Kama Teng',
        'Kama Toh',
    ],
    'Kissi Teng': [
        'Bumasadu',
        'Kundu',
        'Lela',
        'Torli',
    ],
    'Kissi Tongi': [
        'Bende Bengu',
        'Konio',
        'Pokorli',
        'Tongi Tingi',
    ],
    'Komboya': [
        # Possibly two more sections, missing names on map
        'Mangaru',
        'Keisua',
        'Kemoh',
    ],
    'Kongbora': [],
    'Kori': [],
    'Koya': [
        'Joi',
        'Koya Gbundohun',
        'Menima',
        'Serabu',
        'Upper Koya',
    ],
    'Kpaka': [],
    'Kpanda Kemo': [
        'Ba-Kobotu',
        'Bewoni',
        'Gbonge',
        'Senjehun',
        'Sewama',
        'Taokunor',
    ],
    'Kpanga Krim': [],
    'Kpanga Krim/Kabondeh': [],
    'Kpeje Bongre': [
        'Bongre',
        'Borku',
        'Falloh',
        'Jorwu',
        'Manowa',
        'Marwei',
        'Seimaya',
    ],
    'Kpeje West': [
        'Bunumbu',
        'Golama',
        'Kpaewa',
        'Kpindima',
    ],
    'Kunike': [],
    'Kunike Barina': [],
    'Kwamebai Krim': [
        'Kpanga Koimato',
        'Kwako Lanten',
        'Massa Settie',
        'Mosenten Sahen 2',
        'Tubla',
        'Tun-Tun Sullay',
        'Yikie Karbay',
    ],
    'Langrama': [
        'Korjei',
        'Njeiwoma',
    ],
    'Lei': [],
    'Libeisaygahun': [
        'Batkanu',
        'Mafonda',
        'Magbaingba',
        'Magbanamba',
        'Makaiba',
        'Makayrembay',
        'Mandawahun',
        'Manyakoi',
        'Mayankay',
        'Robaka',
        'Rotha-Tha',
        'Simbaya',
    ],
    'Lower Bambara': [
        'Bonya',
        'Fallay',
        'Gboro',
        'Korjei Buima',
        'Korjei Ngieya',
        'Nyawa',
        'Sei',
    ],
    'Luawa': [
        'Gao',
        'Gbela',
        'Giehun',
        'Lower Kpombali',
        'Luawa Foguiya',
        'Mano-Sewallu',
        'Mende Buima',
        'Mofindor',
        'Upper Kpombali',
    ],
    'Lugbu': [
        # Possibly one more section, missing name on map
        'Gao',
        'Kamba',
        'Kargbevu',
        'Magbao',
        'Yorma',
    ],
    'Mafindor': [],
    'Maforki': [],
    'Magbema': [
        'Bombe',
        'Kamba',
        'Kambia',
        'Kargbulor',
        'Robat',
        'Rokupr',
        'Tormina',
    ],
    'Magbaimba Ndorh': [
        'Hunduwa',
        'Kababala',
        'Kagberay',
        'Kawungulu',
        'Makendema',
        'Mambiama',
        'Manjahagha',
        'Sokudala',
        'Yana',
    ],
    'Makari Gbanti': [
        'Gborbana',
        'Mabanta',
        'Magbenteh',
        'Mangay',
        'Mankene',
        'Masongbo A',
        'Masongbo B',
        'Punthun',
        'Rosint',
        'Tonkoba',
        'Yainkassa',
    ],
    'Makpele': [],
    'Malal Mara': [],
    'Malegohun': [
        'Hulorhun Njagbudor',
        'Hulorhun Njeigor',
        'Konjo Buiima',
        'Konjo Njeigor',
        'Konjo Yematanga',
        'Lower Torgboma',
        'Upper Torgboma',
    ],
    'Malema': [
        'Bamburu',
        'Lower Sami',
        'Njagbla',
        'Pelegbambeima',
        'Upper Sami',
    ],
    'Malen': [],
    'Mambolo': [
        'Kalenkay',
        'Mambolo'
        'Matetie',
        'Mayakie',
        'Robis',
        'Rowollon',
        'Tombo-Wallah',
    ],
    'Mandu': [
        'Gbongre',
        'Levuma Jeibla',
        'Lower Kuiva',
        'Upper Kuiva',
    ],
    'Mano Dasse': [],
    'Marampa': [],
    'Masungbala': [
        'Bamoi',
        'Benna',
        'Kawula',
        'Kayenkassa',
        'Mapolon',
        'Maserie',
        'Matengha',
        'Matilba',
        'Nonko',
        'Samu',
        'Sumbuya',
        'Thalla',
    ],
    'Moindekoh': [],
    'Mongo': [
        'Benadugu',
        'Deldugu',
        'Mankalia',
        'Mofgindugu',
        'Mongo 1',
        'Mongo 2',
    ],
    'Ngoleima': [],
    'Niawa': [
        'Bandawor',
        'Kpatawa',
        'Mabondor',
        'Niawa',
        'Vaama',
    ],
    'Niawa Lenga': [
        # Possibly one more section, missing name on map
        'Baimba',
        'Yalenga',
    ],
    'Nieni': [],
    'Nimikoro': [],
    'Nimiyama': [],
    'Njakor': [],
    'Njala Komboya': [],
    'Njaluahun': [
        'Bombowa',
        'Dan Sei',
        'Falley',
        'Fauya',
        'Gboo',
        'Jonga',
        'Kargbu',
        'Keimaya',
        'Lower Nyawa',
        'Sei 1',
        'Sei 2',
        'Upper Nyawa',
    ],
    'Nomo': [
        'Faama',
        'Ngeibu',
        'Ngiewoma-Njeigor',
    ],
    'Nongoba Bullom': [
        'Baoma',
        'Bohol',
        'Bullom',
        'Garinga',
        'Gbangbassa',
        'Gbap',
        'Hahun',
        'Kessie',
        'Manyime',
        'Pelewahun',
        'Salma',
        'Solon',
        'Torma Subu',
    ],
    'Nongowa': [
        'Dagbanya',
        'Dakpana',
        'Gbo Kakajama B',
        'Gbo Lambayama B',
        'Kagbado Kamboima',
        'Kagbado Njeigbla',
        'Kona Foiya',
        'Kona Kpindibu',
    ],
    'Nyango': [],
    'Owawor': [],
    'Paki Masabong': [
        'Kathanthan',
        'Kathegaya',
        'Mapaki',
        'Masabong',
        'Mayagba',
        'Rosanda',
    ],
    'Peje': [],
    'Penguia': [
        'Bulima',
        'Jagor',
        'Kumatandu',
        'Lombama',
        'Nimima',
    ],
    'Pesseh': [],
    'Saaba': [],
    'Safroko Limba': [
        'Binkolo',
        'Bombali Bana',
        'Kabonka',
        'Kasengben',
        'Kayassi',
        'Mabamba',
        'Masapi',
    ],
    'Sakrim': [],
    'Sambaia': [],
    'Samu': [
        'Bubuya',
        'Kassiri',
        'Koya',
        'Kychom',
        'Lusenia',
        'Mafufuneh',
        'Makuma',
        'Mange',
        'Mapotolon',
        'Moribaia',
        'Rokon',
        'Rosinor',
    ],
    'Sanda Loko': [
        'Banka',
        'Benia',
        'Kaindema',
        'Kamalu',
        'Kindia',
        'Laminaya',
        'Madina',
        'Maharibo',
        'Makapa',
        'Makwie Loko',
        'Manathi',
        'Maparay',
        'Rothatha',
        'Timbo',
    ],
    'Sanda Tendaran': [
        'Kukuna',
        'Marampa',
        'Masisan',
        'Mateboi',
        'Rogbin',
        'Rogboreh',
        'Rosos',
        'Sendugu',
        'Yankabala',
    ],
    'Sandor': [],
    'Selenga': [
        'Kaduawo',
        'Mokpehdeh',
        'Old Town',
    ],
    'Sella Limba': [
        'Samia',
        'Kayimbor',
        'Kamakwie',
        'Magbonkoni 1',
        'Manonkoh',
        'Magbonkoni 2',
        'Kamankoh',
    ],
    'Sengbe': [],
    'Simbaru': [
        'Bundoryama',
        'Yalenga',
    ],
    'Sittia': [
        'Bamba',
        'Gonoh',
        'Kamai',
        'Kwalloh',
        'Moh',
        'Saama',
        'Sahaya',
        'Sahn-Gbengu',
        'Sampoh',
        'Yoni',
    ],
    'Small Bo': [
        # Possibly three more sections, names missing on map
        'Kamboma',
        'Sowa',
    ],
    'Soa': [],
    'Sogbeni': [
        'Bakumba',
        'Beyorgboh',
        'Ndopie',
        'Pengor',
    ],
    'Soro Gbema': [],
    'Sowa': [],
    'Sulima': [],
    'T.M. Safroko': [],
    'Taama Forest': [],
    'Tambakha': [
        'Dugutha',
        'Moria',
        'Paramount Chief Se',
        'Simibue',
        'Thalla',
    ],
    'Tane': [],
    'Tankoro': [],
    'Tikonko': [
        'Bainyawa',
        'Mambawa',
        'Morku',
        'Ngolamajie',
        'Njagbla 1',
        'Njagbla 2',
        'Seiwa',
        'Sendeh',
    ],
    'Timdale': [],
    'Toli': [],
    'Tonko Limba': [
        'Bubuya',
        'Kamassassa',
        'Kathanthineh',
        'Magbonkoh',
        'Mamankoh',
        'Yebaya',
    ],
    'Tunkia': [
        'Daru',
        'Gegbwema',
        'Giewoma',
        'Gorahun',
        'Jewahun',
        'Kuawuma',
        'Taninahun',
    ],
    'Upper Bambara': [
        'Bambara',
        'Bomaru-guma',
        'Goleiwoma',
        'Golu',
        'Korbu',
        'Naiahun',
    ],
    'Valunia': [
        'Deilenga',
        'Kendebu',
        'Lunia',
        'Ngovo',
        'Seilenga',
        'Vanjelu',
        'Yarlenga',
    ],
    'Wara-Wara Bafodea': [],
    'Wara-Wara Yagala': [],
    'Woefeh': [],
    'Wonde': [
        'Central Kargoi',
        'Lower Kargoi',
        'Manye',
        'Upper Kargoi',
    ],
    'Wandor': [
        # May be one more section, name missing on map
        'Boryongor',
        'Gbogbeima',
        'Kemoh',
        'Songhai',
        'Tongorwa',
    ],
    'Yawbeko': [
        # Possibly one more section, name missing on map
        'Baryegbe',
        'Ketaway',
        'Mobulie',
        'Yorma',
    ],
    'Yawei': [
        'Kuiva Jagor',
        'Kuivawa',
        'Bendu',
        'Kuiva Buima',
    ],
    'Yoni': [],
}


#
# Reverse mappings (smaller -> larger)
#
district2province = {
    district: province
    for province, districts in province2districts.items()
    for district in districts
}
chiefdom2district = {
    chiefdom: district
    for district, chiefdoms in district2chiefdoms.items()
    for chiefdom in chiefdoms
}

section2chiefdom = {
    section: chiefdom
    for chiefdom, sections in chiefdom2sections.items()
    for section in sections
}


#
# Lists
#
provinces = sorted(province2districts.keys())
districts = sorted(district2chiefdoms.keys())
