"""
References:
    - https://en.wikipedia.org/wiki/Subdivisions_of_Sierra_Leone
    - https://en.wikipedia.org/wiki/Districts_of_Sierra_Leone
    - https://en.wikipedia.org/wiki/Chiefdoms_of_Sierra_Leone
    - https://reliefweb.int/updates?source=1503&format=12.12570&advanced-search=(PC211)#content

Notes:
    - Two new districts, Falaba and Karene, were introduced in 2017.
        - https://en.wikipedia.org/wiki/Falaba_District
        - https://en.wikipedia.org/wiki/Karene_District
        - The number of Chiefdoms also increased from 149 to 190.
        - We are concerned with the structure from 2014.

Issues:
    - How to handle Bo Town. It's not really a Chiefdom, but seems to be a separate entity?
        - Seems to be split into 3 Wards, each with several sections.
    - Do the Western Urban and Western Rural districts have Chiefdoms?
"""

#
# Forward mappings (larger -> smaller)
#
province2districts = {
    'Eastern': ['Kailahun', 'Kenema', 'Kono'],
    'North West': ['Kambia', 'Karene', 'Port Loko'],
    'Northern': ['Bombali', 'Falaba', 'Koinadugu', 'Tonkolili'],
    'Southern': ['Bo', 'Bonthe', 'Moyamba', 'Pujehun'],
    'Western': ['Western Rural', 'Western Urban'],
}

district2chiefdoms = {
    'Bo': [
        'Badjia',
        'Bagbo',
        'Bagbwe',
        'Baoma',
        'Bumpe Ngao',
        'Gbo',
        'Jaiama Bongor',
        'Kakua',
        'Komboya',
        'Lugbu',
        'Niawa Lenga',
        'Selenga',
        'Tikonko',
        'Valunia',
        'Wonde',
    ],
    'Bombali': [
        'Biriwa',
        'Bombali Shebora',
        'Gbanti Kamaranka',
        'Gbendembu Ngowahun',
        'Libeisaygahun',
        'Magbaiamba Ndowahun',
        'Makari Gbanti',
        'Paki Massabong',
        'Safroko Limba',
        'Sanda Loko',
        'Sanda Tenraren',
        'Sella Limba',
        'Tambakha',
    ],
    'Bonthe': [
        'Bendu',
        'Bum',
        'Dema',
        'Imperri',
        'Jong',
        'Kongoba Bullom',
        'Kpanda',
        'Kwamebai Krim',
        'Sittia',
        'Songbini',
        'Yawbeko',
    ],
    'Kailahun': [
        'Dea',
        'Jaluahun',
        'Jawei',
        'Kissi Kama',
        'Kissi Teng',
        'Kissi Tongi',
        'Luawa',
        'Malema',
        'Mandu',
        'Peje Bongre',
        'Peje West',
        'Penguia',
        'Upper Bambara',
        'Yawei',
    ],
    'Kambia': [
        'Brimaia',
        'Gbinle Dixing',
        'Magbema',
        'Mambolo',
        'Masungbala',
        'Samu',
        'Tonko Limba',
    ],
    'Kenema': [
        'Dama',
        'Dodo',
        'Gaura',
        'Gorama Mende',
        'Kandu Leppiam',
        'Koya',
        'Langurama Ya',
        'Lower Bambara',
        'Malegohun',
        'Niawa',
        'Nomo',
        'Nongowa',
        'Simbaru',
        'Small Bo',
        'Tunkia',
        'Wando',
    ],
    'Koinadugu': [
        'Dembelia Sikunia',
        'Diang',
        'Folasaba',
        'Kasunko',
        'Mongo',
        'Neya',
        'Nieni',
        'Sengbe',
        'Sulima',
        'Wara-Wara Bafodea',
        'Wara-Wara Yagala',
    ],
    'Kono': [
        'Fiama',
        'Gbane Kandor',
        'Gbane',
        'Gbense',
        'Gorama Kono',
        'Kamara',
        'Lei',
        'Mafindor',
        'Nimikoro',
        'Nimiyama',
        'Sandor',
        'Soa',
        'Tankoro',
        'Toli',
    ],
    'Moyamba': [
        'Bagruwa',
        'Banta',
        'Bumpe',
        'Dasse',
        'Fakunya',
        'Kagboro',
        'Kaiyamba',
        'Kamajei',
        'Kongbora',
        'Kori',
        'Kowa',
        'Ribbi',
        'Timdale',
        'Upper Banta',
    ],
    'Port Loko': [
        'Bureh Kasseh',
        'Buya Romende',
        'Debia',
        'Kaffu Bullom',
        'Koya',
        'Loko Masama',
        'Maforki',
        'Marampa'
        'Masimera',
        'Sanda Magbolontor',
        'T.M. Safroko',
    ],
    'Pujehun': [
        'Barri',
        'Gallines Perri',
        'Kpaka',
        'Kpanga Kabonde',
        'Kpanga Krim',
        'Makpele',
        'Malen',
        'Mano Sa Krim',
        'Peje',
        'Soro Gbema',
        'Sowa',
        'Yakemo Kpukumu Krim',
    ],
    'Tonkolili': [
        'Gbonkolenken',
        'Kafe Simiria',
        'Kalansongoia',
        'Kholifa Mabang',
        'Kholifa Rowalla',
        'Kunike Barina',
        'Kunike',
        'Malal Mara',
        'Sambaia',
        'Tane',
        'Yoni',
    ],
    'Western Rural': [
        'Koya Rural',
        'Mountain Rural',
        'Waterloo Rural',
        'York Rural',
    ],
    'Western Urban': [
        'Central 1',
        'Central 2',
        'East 1',
        'East 2',
        'East 3',
        'West 1',
        'West 2',
        'West 3',
    ],
}

chiefdom2sections = {
    'Badjia': [
        # Possibly one more section, missing name on map
        'Damal',
        'Kpallay',
        'Njargbahun',
        'Sei',
    ],
    'Bagbo': [
        'Bum',
        'Gorapon',
        'Jimmi',
        'Kpangballa',
        'Mano',
        'Niagorehun',
        'Tissana',
    ],
    'Bagbwe': [
        # Possibly one more section, missing name on map
        'Jongo',
        'Niawa',
        'Nyallay',
        'Samawa',
    ],
    'Baoma': [
        'Bambawo',
        'Fallay',
        'Kimaya',
        'Lower Pataloo',
        'Mawojeh',
        'Njeima',
        'Sonnah',
        'Upper Pataloo',
    ],
    'Bapewa': [],
    'Barri': [],
    'Benducha': [],
    'Biriwa': [
        'Balandugu',
        'Bumban',
        'Bumbandain',
        'Kabakeh',
        'Kagbankuna',
        'Kamabai',
        'Karassa',
        'Karina',
        'Kayonkoro',
    ],
    'Bombali Shebora': [],
    'Bonthe Municipal': [],
    'Bramaia': [],
    'Bum': [],
    'Bumpe': [],
    'Bumpe Ngao': [
        'Bongo',
        'Bumpe',
        'Foya',
        'Kpetema',
        'Sahn',
        'Serabu',
        'Sewama',
        'Taninahun',
        'Walihun',
        'Yengema',
    ],
    'Buya Romende': [],
    'Chepo': [],
    'Dasse': [],
    'Dea': [],
    'Debia': [],
    'Dema': [],
    'Dembelia Sikunia': [],
    'Diang': [],
    'Fakunya': [],
    'Fiama': [],
    'Folosaba Dembelia': [],
    'Gallines Perri': [],
    'Gbakahun': [],
    'Gbane': [],
    'Gbane Kandor': [],
    'Gbanti Kamaranka': [],
    'Gbap': [],
    'Gbayafe': [],
    'Gbendembu Ngowahun': [],
    'Gbense': [],
    'Gbinleh Dixing': [],
    'Gbo': [
        'Gbo',
        'Maryu',
        'Nyawa',
    ],
    'Gbomoti': [],
    'Gbonkolenken': [],
    'Gorama Kono': [],
    'Imperri': [],
    'Jaiama Bongor': [
        'Lower Baimba',
        'Lower Kama',
        'Lower Niawa',
        'Nekpondo',
        'Tongowa',
        'Upper Baimba',
        'Upper Kama',
        'Upper Niawa',
    ],
    'Jaluahun': [],
    'Jassande Keifema': [],
    'Jawei': [],
    'Jong': [],
    'Kafe Simiria': [],
    'Kaffu-Bullom': [],
    'Kaiyamba': [],
    'Kaiyamba Fakunya': [],
    'Kakua': [
        # Possibly two more sections, missing names on map
        'Korjeh',
        'Kpandobu',
        'Nguabu',
        'Samamie',
        'Sewa',
        'Sindeh',
    ],
    'Kalansogoia': [],
    'Kamara': [],
    'Kasunko': [],
    'Kemoh': [],
    'Kholifa Mabang': [],
    'Kholifa Rowalla': [],
    'Kissi Kama': [],
    'Kissi Teng': [],
    'Kissi Tongi': [],
    'Komboya': [
        # Possibly two more sections, missing names on map
        'Mangaru',
        'Keisua',
        'Kemoh',
    ],
    'Kongbora': [],
    'Kori': [],
    'Koya': [],
    'Kpaka': [],
    'Kpanda Kemo': [],
    'Kpanga Krim': [],
    'Kpanga Krim/Kabondeh': [],
    'Kunike': [],
    'Kunike Barina': [],
    'Kwamebai Krim': [],
    'Lei': [],
    'Libeisaygahun': [],
    'Luawa': [],
    'Lugbu': [
        # Possibly one more section, missing name on map
        'Gao',
        'Kamba',
        'Kargbevu',
        'Magbao',
        'Yorma',
    ],
    'Mafindor': [],
    'Maforki': [],
    'Magbema': [],
    'Makari Gbanti': [],
    'Makpele': [],
    'Malal Mara': [],
    'Malema': [],
    'Malen': [],
    'Mambolo': [],
    'Mandu': [],
    'Mano Dasse': [],
    'Marampa': [],
    'Masungbala': [],
    'Moindekoh': [],
    'Ngoleima': [],
    'Niawa Lenga': [
        # Possibly one more section, missing name on map
        'Baimba',
        'Yalenga',
    ],
    'Nieni': [],
    'Nimikoro': [],
    'Nimiyama': [],
    'Njakor': [],
    'Njala Komboya': [],
    'Nongoba Bullom': [],
    'Nyango': [],
    'Owawor': [],
    'Paki Massabong': [],
    'Peje': [],
    'Peje Bongre': [],
    'Peje West': [],
    'Pesseh': [],
    'Saaba': [],
    'Safroko Limba': [],
    'Safroko Limba(Kalasokia)': [],
    'Safroko Limba(Makateh': [],
    'Sakrim': [],
    'Sambaia': [],
    'Sanda Loko': [],
    'Sanda Tendaren': [],
    'Sandor': [],
    'Selenga': [
        'Kaduawo',
        'Mokpehdeh',
        'Old Town',
    ],
    'Sella Limba': [],
    'Sengbe': [],
    'Sittia': [],
    'Soa': [],
    'Sogbini': [],
    'Soro Gbema': [],
    'Sowa': [],
    'Sulima': [],
    'T.m. Safroko': [],
    'Taama Forest': [],
    'Tane': [],
    'Tankoro': [],
    'Tikonko': [
        'Bainyawa',
        'Mambawa',
        'Morku',
        'Ngolamajie',
        'Njagbla 1',
        'Njagbla 2',
        'Seiwa',
        'Sendeh',
    ],
    'Timdale': [],
    'Toli': [],
    'Tonko Limba': [],
    'Upper Bambara': [],
    'Valunia': [
        'Deilenga',
        'Kendebu',
        'Lunia',
        'Ngovo',
        'Seilenga',
        'Vanjelu',
        'Yarlenga',
    ],
    'Wara-Wara Bafodea': [],
    'Wara-Wara Yagala': [],
    'Woefeh': [],
    'Wonde': [
        'Central Kargoi',
        'Lower Kargoi',
        'Manye',
        'Upper Kargoi',
    ],
    'Yawbeko': [],
    'Yoni': [],
}


#
# Reverse mappings (smaller -> larger)
#
district2province = {
    district: province
    for province, districts in province2districts.items()
    for district in districts
}
chiefdom2district = {
    chiefdom: district
    for district, chiefdoms in district2chiefdoms.items()
    for chiefdom in chiefdoms
}

section2chiefdom = {
    section: chiefdom
    for chiefdom, sections in chiefdom2sections.items()
    for section in sections
}


#
# Lists
#
provinces = sorted(province2districts.keys())
districts = sorted(district2chiefdoms.keys())
